sudo: false
language: python

matrix:
  include:
    - python: "2.7"
      env: DJANGO_VERSION="Django>=1.11,<2.0"
    - python: "3.4"
      env: DJANGO_VERSION="Django>=2.0,<2.1"
    - python: "3.5"
      env: DJANGO_VERSION="Django>=2.0,<2.1"
    - python: "3.6"
      env: DJANGO_VERSION="Django>=2.0,<2.1"

install:
  - pip install -q --upgrade $DJANGO_VERSION
  - pip install coveralls

script:
  - coverage run --source=dbstorage manage.py test

after_success:
  - coveralls
